# .readthedocs.yml
version: 2
build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"
  # Uncomment this and any needed lines below if your project has dependencies needed for install
  # apt_packages:
  #   - mpich
  jobs:
    post_create_environment:
      # Install poetry
      - pip install poetry
    post_install:
      # Install project and dependencies with 'docs' dependency group.
      - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH poetry install --with docs
      # Generate API documentation, etc. (if needed)
      - make -f docs/Makefile content
sphinx:
  configuration: docs/conf.py
