# Please see the notes for developers for more information about this project's
#   policy in regards to the use of git hooks.  For more information about the
#   pre-commit framework, please see: https://pre-commit.com
#
# To get started with them is this project yourself, simply run: pre-commit install

repos:

  # Some minor quality of life things
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: no-commit-to-branch
        args: ['--branch', 'main'] # Commits to main only allowed VIA PR for this project

  # Ensure that revisions for tools such as ruff, black, etc. can be
  #   managed by Poetry but synced here before commiting code
  - repo: https://github.com/floatingpurr/sync_with_poetry
    rev: 1.1.0
    hooks:
      - id: sync_with_poetry
        args: ['--db','.pre-commit-db.json']

  # Format code
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black

  # Lint code
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.5.0
    hooks:
      - id: ruff

  # Make sure the Poetry project is properly maintained
  - repo: https://github.com/python-poetry/poetry
    rev: 1.8.0
    hooks:
      - id: poetry-check
      - id: poetry-lock
